### ISSUE TITLE
with latest node version error 

### ISSUE THREAD

**Issue by delmarle** [jirkadev/shrimpy-refollow-script#1]
shrimpy-refollow-script-master % node index.js
shrimpy-refollow-script-master/node_modules/tough-cookie/lib/cookie.js:457
  str = str.trim();
            ^

TypeError: Cannot read property 'trim' of undefined
    at Function.parse (/Users/username/Downloads/shrimpy-refollow-script-master/node_modules/tough-cookie/lib/cookie.js:457:13)
    at Object.<anonymous> (/Users/username/Downloads/shrimpy-refollow-script-master/index.js:13:29)

**Comment by jirikrepl** [comment]
ok, are you setting up the cookie in .env file correctly?

Sorry, there's no readme. But you need to copy .env-sample to .env file and then correctly set all env variables.

**Comment by delmarle** [comment]
i dont see those files, could you tell me where they are supposed to be ?

**Comment by delmarle** [comment]
ok after showing hidden files i can see the env file but im not sure what do i get information for those:

LEADER_ID=7...
USER_ID=auth0|...
COOKIE=connect.sid=s:...
REBALANCE_INFO_ID=1...
EXCHANGE_ACCOUNT_ID=1...
LEADER_REBALANCE_INFO_ID=7...

**Comment by jirikrepl** [comment]
basically, the script is using one GET request to get balances
and two POST requests to stop-follow and start-follow.

Shrimpy frontend use these requests (e.g. if you click on Stop follow it will do `portfolio_deactivate` POST request)
You need to open chrome inspector and go to the Network tab.

Then you need to start recording network activity.
If you click on the stop follow button you should see the `portfolio_deactivate` request.
If you open it you will see the values you need.
